name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all
          
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run auto tests
    steps:
      - name: Check out autotests
        uses: actions/checkout@v6
      - name: Set up Python env
        uses: actions/setup-python@v6
        with:
           python-version: '3.14'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression
      - name: Run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended
        
