name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all
          
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run auto tests
    steps:
      - name: Check out autotests
        uses: actions/checkout@v6
      - name: Set up Python env
        uses: actions/setup-python@v6
        with:
           python-version: '3.14'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
      - name: Run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: check java
        run: java --version
      # 2. Install dependencies (including Allure)
      - name: Install Allure
        run: wget https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz 
      - name: unzip tar
        run: tar -zxvf allure-2.33.0.tgz -C /opt/
      - name: check unzip
        run: ls -l /opt
      - name: make link
        run: sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
      - name: check PATH
        run: echo $PATH
      - name: check allure
        run: /usr/local/bin/allure --version # Verify installation
      - name: Generate Allure report
        run: /usr/local/bin/allure generate -c allure-results -o allure-report
      - name: Save Allure report
        uses: actions/upload-artifact@v7
        with:
          name: allure-report
          path: allure-report
          retention-days: 2
          
        
