name: Auto test ver 2(with standart actions)

# when to run
on:
  push: # when commin to main done
    branches:
      - main
  pull_request: # when pull request to main done
    branches:
      - main    
  workflow_dispatch: # manual from guthub Actions
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

permissions: 
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: check-out repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'
       
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -m regression --alluredir=allure-results

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.13
#        uses: ./
#        if: always()
        with:
#          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
#        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
