name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all
          
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run auto tests
    steps:
      - name: Check out autotests
        uses: actions/checkout@v6
      - name: Set up Python env
        uses: actions/setup-python@v6
        with:
           python-version: '3.14'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: Run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'
      # 2. Install dependencies (including Allure)
      - name: Install Allure
        run: wget https://github.com/allure-framework/allure2/releases/download/2.38.1/allure-2.38.1.tgz 
      - name: unzip tar
        run: tar -zxvf allure-2.38.1.tgz -C /opt/
      - name: make link
        run: sudo ln -s /opt/allure-2.38.1/bin/allure /usr/local/bin/allure
      - name: Generate Allure report
        run: allure generate -c allure-results -o _site
      - name: Save Allure report
        uses: actions/upload-artifact@v6
        with:
          name: _site
          path: _site
          retention-days: 2
          
  publish-report:
    name: Report publication 
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v8
     - name: Upload Pages artifact
       uses: actions/upload-pages-artifact@v4
     - name: Deploy to github Pages
       id: deployment
       uses: actions/deploy-pages@v4
  
          
        
